---
extends: "airbnb"
rules:
  func-names:
    - 0
  prefer-arrow-callback:
    - 0
  no-var:
    - 0
  no-console:
    - 0
  no-undef:
    - 0
ecmaFeatures:
  modules: true
env:
  es6: false
  node: true
